# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitResume < Formula
  desc "CLI to summarize git commits using AI"
  homepage "https://github.com/guilhermezuriel/git-resume"
  version "4.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guilhermezuriel/git-resume/releases/download/v4.1.0/git-resume_darwin_amd64.tar.gz"
      sha256 "c7ceaebc217d581e5bc5a33aa4f7032782e622cb3551f246f150958a9232e608"

      define_method(:install) do
        bin.install "git-resume"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guilhermezuriel/git-resume/releases/download/v4.1.0/git-resume_darwin_arm64.tar.gz"
      sha256 "ad863c1a032912d33c4056ab47fbb28a7c2cc9eb7a774ce5209e30c0ae2918a3"

      define_method(:install) do
        bin.install "git-resume"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/guilhermezuriel/git-resume/releases/download/v4.1.0/git-resume_linux_amd64.tar.gz"
      sha256 "ec12b4bf5977f63d9c660b3e3a1973c0e743e60a3abba936361c9534a6fc8902"
      define_method(:install) do
        bin.install "git-resume"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guilhermezuriel/git-resume/releases/download/v4.1.0/git-resume_linux_arm64.tar.gz"
      sha256 "a269acce13d9cc44b16eb76ed4a39c03155897f7ddd71e15803f8b0b22cc7591"
      define_method(:install) do
        bin.install "git-resume"
      end
    end
  end
end
