# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitResume < Formula
  desc "CLI to summarize git commits using AI"
  homepage "https://github.com/guilhermezuriel/git-resume"
  version "3.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guilhermezuriel/git-resume/releases/download/v3.0.4/git-resume_darwin_amd64.tar.gz"
      sha256 "4190a3f19ed8e264f12e6a83686146395fc41fb8a9fda806c3a21006e4c41452"

      define_method(:install) do
        bin.install "git-resume"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guilhermezuriel/git-resume/releases/download/v3.0.4/git-resume_darwin_arm64.tar.gz"
      sha256 "c268a982fff403e08f7a6ef995493b0e87e8138a108ca6f3db9d0e6f59dec026"

      define_method(:install) do
        bin.install "git-resume"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/guilhermezuriel/git-resume/releases/download/v3.0.4/git-resume_linux_amd64.tar.gz"
      sha256 "da5ab404ce458dfc2e4fa67443630109a8de8e6315aaae182ca705a6f957544b"
      define_method(:install) do
        bin.install "git-resume"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guilhermezuriel/git-resume/releases/download/v3.0.4/git-resume_linux_arm64.tar.gz"
      sha256 "4780f42f51371ffff8ed33557a6da1f2989d823486481824943160b73039f1fe"
      define_method(:install) do
        bin.install "git-resume"
      end
    end
  end
end
